version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./application:/application"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0
